name: Release Tag

on:
  push:
    tags:
      - "v*"

concurrency:
  group: "kordex-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'Kord-Extensions/kord-extensions'

    env:
      GPG_KEY_NAME: BFAAD5D6093EF5E62BC9A16A10DB8C6B4AE61C2F

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@1694fbd49c38ab354ff58e249fe2d73d74a1c6eb # v1.2

      - name: SonarQube (Cache)
        uses: actions/cache@v4

        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-XX:MaxMetaspaceSize=5G" >> ~/.gradle/gradle.properties
          echo -e "\nsigning.gnupg.keyName=${{ env.GPG_KEY_NAME }}" >> ~/.gradle/gradle.properties
          echo -e "\nsigning.gnupg.passphrase=${{ secrets.GPG_PASSWORD }}" >> ~/.gradle/gradle.properties

      - name: Set up git credentials
        uses: oleksiyrudenko/gha-git-credentials@8bb1fe6d543b2233ef1856cd3b0181f5abbd4d6a # v2.1.2

        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

        with:
          package_json_file: modules/web/web-core/web-frontend/package.json
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4

        with:
          node-version-file: modules/web/web-core/web-frontend/package.json
          cache-dependency-path: modules/web/web-core/web-frontend/pnpm-lock.yaml
          cache: 'pnpm'

      - name: Gradle (Build)
        run: "./gradlew checkLicenses build koverXmlReport sonar"

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

          TOKEN: "${{ secrets.TOKEN }}"

      - name: Gradle (Publish)
        run: "./gradlew publish"

        env:
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.GPG_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.GPG_PASSWORD }}"

          OSSRH_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
          OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"

          KORDEX_MAVEN_USERNAME: "${{ secrets.KORDEX_MAVEN_USERNAME }}"
          KORDEX_MAVEN_PASSWORD: "${{ secrets.KORDEX_MAVEN_PASSWORD }}"

          TOKEN: "${{ secrets.TOKEN }}"

      - name: Create release description
        run: kotlin .github/tag.main.kts

      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=NAME::${GITHUB_REF#refs/tags/}

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          body_path: release.md
          name: Release ${{ steps.get_tag.outputs.NAME }}

          files: |
            annotations/*/build/libs/*.jar
            kord-extensions/build/libs/*.jar
            modules/**/build/libs/*.jar
            token-parser/build/libs/*.jar

      - name: Release webhook
        run: kotlin .github/release.main.kts

        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Upload artifact (Core JARs)
        uses: actions/upload-artifact@v4

        with:
          name: JARs (Core)
          path: kord-extensions/build/libs/*.jar

      - name: Upload artifact (Annotation JARs)
        uses: actions/upload-artifact@v4

        with:
          name: JARs (Annotation)
          path: annotations/**/build/libs/*.jar

      - name: Upload artifact (Module JARs)
        uses: actions/upload-artifact@v4

        with:
          name: JARs (Modules)
          path: modules/**/build/libs/*.jar

      - name: Upload artifact (Parser JARs)
        uses: actions/upload-artifact@v4

        with:
          name: JARs (Parser)
          path: token-parser/build/libs/*.jar

